describe('minicart', () => {
    it('minicart', () => {
        cy.visit(Cypress.env('productPageUrl'))
        cy.get('#st-container-hide > div > div > div.row > div.col-md-10.col-12.product-section-main > div.col-md-12.product-list > div.row > div:nth-child(1) > div > div.product-box > a:nth-child(2) > div').click()
        cy.get('#st-container-hide > div > div.container-fluid.product-detail-container > div.row > div.col-md-5.col-sm-12.content-section.product-details > div:nth-child(6) > div > div.size-box > label:nth-child(2) > span')
        .click()
        cy.get('#product-addtocart-button').click()
        cy.get('#pim_main > span > div.header > div.container-fluid.mobile-list > div > div > div > div.user-logins.col-sm-2.p-0.m-0.pl-0.my-xl-1 > div.user-logins-icons > ul > li:nth-child(4)')
        .click({force:true})
        cy.get("#pim_main > span > div.header > div.container-fluid.mobile-list > div > div > div > div.user-logins.col-sm-2.p-0.m-0.pl-0.my-xl-1 > div.user-logins-icons > ul > li:nth-child(4) > div")
        .invoke('show')
        cy.get('#pim_main > span > div.header > div.container-fluid.mobile-list > div > div > div > div.user-logins.col-sm-2.p-0.m-0.pl-0.my-xl-1 > div.user-logins-icons > ul > li:nth-child(4) > div > div > div:nth-child(3) > a')
        .click()
        cy.wait(1000)
        cy.get('#st-container-hide > div > div.container-fluid.cart-container > div:nth-child(2) > div.col-9.cart-table > table > tbody > tr > td.qty.pl-5 > div > div > a:nth-child(3) > i').click()
        var text  = Cypress.env('updateCart')
        cy.get("body > div.notices.is-top").contains(text)
    })
})