describe('order', () => {
    it('order', () => {
        cy.visit(Cypress.env('orderProduct'))
        cy.get('#st-container-hide > div > div > div.row > div.col-md-10.col-12.product-section-main > div.col-md-12.product-list > div.row > div:nth-child(1) > div > div.product-box > a:nth-child(2) > div').click()
        cy.get('#st-container-hide > div > div.container-fluid.product-detail-container > div.row > div.col-md-5.col-sm-12.content-section.product-details > div:nth-child(6) > div > div.size-box > label:nth-child(2) > span')
        .click()
        cy.get('#product-addtocart-button').click()
        cy.get("#pim_main > span > div.header.product-detailmain > div.container-fluid.mobile-list > div > div > div > div.user-logins.col-sm-2.p-0.m-0.pl-0.my-xl-1 > div.user-logins-icons > ul > li:nth-child(4) > div > div > div:nth-child(4) > a").click()
        cy.get("#login-section > div.loginCenter > form > div.field.mobile > input").type(Cypress.env('mobile'))
        cy.get("#login-section > div.loginCenter > form > div.row.login-tab-width > div:nth-child(2) > button").click()
        cy.get("#login-section > div.loginCenter > form > div.field.otp > input").type(Cypress.env('otp'))
        cy.get("#shipping-address-section > button").click()
        cy.get("#new-address-section > form > div.field.full-name > input").type(Cypress.env('username'))
        cy.get("#new-address-section > form > div.field.street-address > input").type(Cypress.env('address'))
        cy.get("#postcode").type(Cypress.env('pincode'))
        cy.get("#new-address-section > form > div.field.email > input").type(Cypress.env('email'))
        cy.get("#new_address").click()
        cy.get("#old_address").click()
        cy.get("#payment-method-section > div.all_payments > div.payment-method-cod > div > div.payment-method-title.choice").click()
        cy.wait(1000)  
        cy.get("#cashondelivery_button").click()
        cy.url().should('include','/thankyou.html')

    })
})